package com.karrar.movieapp.domain.enums

enum class AllMediaType {
    ON_THE_AIR,
    AIRING_TODAY,
    LATEST,
    POPULAR,
    TOP_RATED,
    TRENDING,
    RECENTLY_RELEASED,
    UPCOMING,
    MYSTERY,
    ADVENTURE,
    ACTOR_MOVIES,

    BASED_ON_TRUE_EVENTS,
    CINEMATIC_MASTERPIECE,
    FAMILY_NIGHT_PICKS,
    FEEL_GOOD_PREFERENCES,
    LATE_NIGHT_THRILLS,
    MIND_BENDING_STORIES
}